# Generated by Django 3.0.5 on 2020-08-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20200815_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingscore',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building'),
        ),
    ]
