# Generated by Django 3.0.5 on 2020-08-15 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0003_auto_20200815_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingscore',
            name='evaluated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
