# Generated by Django 3.0.5 on 2020-08-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20200815_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.AlterField(
            model_name='building',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
