# Generated by Django 3.0.5 on 2020-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_auto_20200815_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='loc_latitude',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='building',
            name='loc_longitude',
            field=models.FloatField(default=1),
        ),
    ]
