# Generated by Django 3.1 on 2020-08-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='due',
        ),
        migrations.AddField(
            model_name='rental',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='app.profile'),
        ),
        migrations.AddField(
            model_name='rental',
            name='deadline',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='left',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='app.profile'),
        ),
    ]
