# Generated by Django 3.1 on 2020-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200815_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
