# Generated by Django 3.0.5 on 2020-08-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200815_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluate',
            name='building',
        ),
        migrations.RemoveField(
            model_name='live',
            name='building',
        ),
        migrations.RemoveField(
            model_name='live',
            name='residence',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Evaluate',
        ),
        migrations.DeleteModel(
            name='Live',
        ),
    ]
