# Generated by Django 3.1 on 2020-08-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200815_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='region',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
