# Generated by Django 3.1 on 2020-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200815_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
