# Generated by Django 3.0.5 on 2020-08-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200815_1727'),
        ('app', '0003_auto_20200815_0823'),
        ('app', '0003_auto_20200815_1040'),
    ]

    operations = [
    ]
