# Generated by Django 3.1 on 2020-08-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200815_1040'),
        ('app', '0008_auto_20200815_1727'),
    ]

    operations = [
    ]
