# Generated by Django 3.1 on 2020-08-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200815_0823'),
        ('app', '0009_merge_20200815_1706'),
    ]

    operations = [
    ]
