# Generated by Django 3.0.5 on 2020-08-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20200815_1806'),
        ('app', '0010_merge_20200815_1803'),
    ]

    operations = [
    ]
